# Generated by Django 5.1.7 on 2025-03-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
