# Generated by Django 5.1.7 on 2025-03-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EV', '0002_customer_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
