# Generated by Django 5.1.7 on 2025-03-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EV', '0004_remove_stations_station_vehicleid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_battery',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
