# Generated by Django 5.1.7 on 2025-03-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EV', '0005_vehicle_vehicle_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='customer_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rides',
            name='vehicle_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
