# Generated by Django 5.1.7 on 2025-03-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EV', '0006_alter_rides_customer_id_alter_rides_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='drop_station_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rides',
            name='pickup_station_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
