# Generated by Django 5.1.7 on 2025-03-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EV', '0007_alter_rides_drop_station_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_penalty',
            field=models.FloatField(default=0, null=True),
        ),
    ]
